# hugo server --minify --themesDir ../..

# for maximum cleanups and rebuilds, run where you checked out the repository
# hugo server --printPathWarnings --disableFastRender --cleanDestinationDir=true --logLevel=debug \
# --gc -M -s exampleSite --themesDir ../.. -b http://127.0.0.1/

baseURL = 'http://0.0.0.0:1313/design-system/'
theme = 'design-system'

# Book configuration
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  title = 'Gurukulams'
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[languages.ta]
  title = "குருகுலங்கள்"
  languageName = 'தமிழ்'
  contentDir = 'content.ta'
  weight = 2

[security]
enableInlineShortcodes = true
[security.funcs]
getenv = ['^HUGO_','CONTEXT','BUILD_PRODUCTION']


[params]
  IncludeFooter = true