# hugo server --minify --themesDir ../..

# for maximum cleanups and rebuilds, run where you checked out the repository
# hugo server --printPathWarnings --disableFastRender --cleanDestinationDir=true --logLevel=debug \
# --gc -M -s exampleSite --themesDir ../.. -b http://127.0.0.1/

baseURL = 'http://localhost:1234/design-system/'
theme = 'design-system'

# Book configuration
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[markup.highlight]
  style = "dracula" # You can choose github-dark, dracula, etc.

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  title = 'Design System'
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[languages.ta]
  title = "வடிவமைப்பு"
  languageName = 'தமிழ்'
  contentDir = 'content.ta'
  weight = 2

[security]
enableInlineShortcodes = true
[security.funcs]
getenv = ['^HUGO_','CONTEXT','BUILD_PRODUCTION']


[params]
  LoginMode = "Google" ## Google, Github


[menu]

# Scenario 1: External Link (GitHub Repository)
[[menu.footer]]
  name = 'GitHub'
  url = 'https://github.com/gurukulams/design-system'
  weight = 1

# Scenario 2: Internal Page with Both English & Tamil Content
[[menu.footer]]
  pageRef = '/license'
  weight = 2

# Scenario 3: Internal Page with ONLY English Content (Missing Tamil file)
[[menu.footer]]
  pageRef = '/contributing'
  weight = 3

# [[menu.footer]]
#   name = 'Showcases'
#   pageRef = 'showcases'
#   weight = 2

# [[menu.footer]]
#   name = 'Github'
#   pageRef = 'showcases'
#   weight = 3